# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdata', '0002_auto_20161124_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='AFDGGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('players', models.ManyToManyField(to='userdata.AFDGUser')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='afdggame_winner', to='userdata.AFDGUser')),
            ],
        ),
    ]
