#!/bin/bash
set -e

function usage() {
    echo -n \
"Usage: $(basename "$0")
Run test suites.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        echo "Testing frontend code"
        pushd afdg-frontend
        elm make src/Main.elm
        popd
    fi
fi
