# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AFDGUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=31)),
                ('wins', models.IntegerField(default=0)),
                ('games', models.IntegerField(default=0)),
            ],
        ),
    ]
